spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/settlement_batch_db?serverTimezone=UTC
      username: settlement_batch_user
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true